/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qpublisher;

// The following code in this files is taken from:
// https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues-getting-started-java.html
import com.amazonaws.AmazonClientException;
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.*;

public class App {

    public static void main(String[] args) {
        final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

        try {
            final CreateQueueRequest createQueueRequest = new CreateQueueRequest("QueueA");
            final String myQueueUrl = sqs.createQueue(createQueueRequest).getQueueUrl();
            sqs.sendMessage(new SendMessageRequest(myQueueUrl,"This is my message text #" + Math.floor(Math.random() * 100) ));
        } catch (final AmazonClientException ace) {
            System.out.println("Error Message: " + ace.getMessage());
        }
    }
}
